### ISSUE TITLE
Realtime not working on local ( using CLI )

### ISSUE THREAD

**Issue by mr-moto** [supabase/realtime#415]
# Bug report

## Describe the bug

Not sure what im doing wrong but when testing out a new project with a local setup, realtime doesnt seem to want to connect. works on a hosted supabase setup.
realtime docker image log: `project=realtime-dev external_id=realtime-dev [error] Auth error: {:error, :signature_error}`.
browser console error returns: `browser.js:25 WebSocket connection to 'ws://localhost:54321/realtime/v1/websocket?apikey=....&vsn=1.0.0' failed`

I have realtime enabled on the table

similar error messages to this [comment](https://github.com/supabase/realtime/issues/372#issuecomment-1372672885) but on a local docker environment using the cli, not self hosted docker.

TIA!

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. `supabase start` on a new project
2. run a standard listener from the docs
```
  supabase
    .channel('public:profiles')
    .on(
      'postgres_changes',
      { event: 'UPDATE', schema: 'public', table: 'profiles' },
      (payload) => {
         console.log('Change received!', payload);
       }
    )
    .subscribe()
```

## Expected behavior

Should subscribe successfully to the table

## System information

- OS: macOS
- Browser (if applies) Chrome
- Version of supabase-js: 2.2.3
- Version of Node.js: 18.12.1

**Comment by itisnajim** [comment]
because of this
https://github.com/supabase/realtime/issues/411

more details see this:
https://github.com/supabase/realtime/issues/372

**Comment by mr-moto** [comment]
@itisnajim thanks for those! I checked those out before posting but was hoping for a workaround with the CLI.  But since the underlying issue is with the realtime docker image, which the CLI uses, I guess we'll have to wait for a fix before the CLI can work properly out of the box.

**Comment by w3b6x9** [comment]
Sorry about this one folks. I'll go and update the image so the `JWT_SECRET` points to the secret set via `API_JWT_SECRET`.

So in the case of the CLI it'll be `"super-secret-jwt-token-with-at-least-32-characters-long"` and in the case of self-hosting over in the supabase/supabase repo it'll be `"your-super-secret-jwt-token-with-at-least-32-characters-long`". You can set `API_JWT_SECRET` to whatever you want and Realtime will just work.

In the meantime, you can update the secret locally by issuing a `PUT` request:

```bash
  curl -X PUT \
  -H 'Content-Type: application/json' \
  -H 'Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiIiLCJpYXQiOjE2NzEyMzc4NzMsImV4cCI6MTcwMjc3Mzk5MywiYXVkIjoiIiwic3ViIjoiIn0._ARixa2KFUVsKBf3UGR90qKLCpGjxhKcXY4akVbmeNQ' \
  -d $'{
    "tenant" : {
      "name": "realtime-dev",
      "external_id": "realtime-dev",
      "jwt_secret": "super-secret-jwt-token-with-at-least-32-characters-long",
      "extensions": [
        {
          "type": "postgres_cdc_rls",
          "settings": {
            "db_name": "postgres",
            "db_host": "host.docker.internal",
            "db_user": "postgres",
            "db_password": "postgres",
            "db_port": "5432",
            "region": "us-west-1",
            "poll_interval_ms": 100,
            "poll_max_record_bytes": 1048576,
            "ip_version": 4
          }
        }
      ]
    }
  }' \
  http://localhost:4000/api/tenants/realtime-dev
```

You can also create other tenants by following the instructions found here: https://github.com/supabase/realtime#server-setup.

**Comment by dberecz** [comment]
@w3b6x9 I tried your fix after it got merged to develop by creating a new docker image from develop and updating the docker compose file to use that locally built image. I did not change anything else in the compose, all default. However, I still receive errors for Postgres Changes:
`realtime-dev.supabase-realtime  | 10:22:51.070 project=realtime-dev external_id=realtime-dev [error] Auth error: {:error, :signature_error}
supabase-kong                   | 172.18.0.1 - - [10/Jan/2023:10:22:51 +0000] "GET /realtime/v1/websocket?apikey=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyAgCiAgICAicm9sZSI6ICJhbm9uIiwKICAgICJpc3MiOiAic3VwYWJhc2UtZGVtbyIsCiAgICAiaWF0IjogMTY0MTc2OTIwMCwKICAgICJleHAiOiAxNzk5NTM1NjAwCn0.dc_X5iR_VP_qT0zsiyj_I_OZ2T9FtRU2BBNWN8Bu4GE&vsn=1.0.0 HTTP/1.1" 403 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"`

I have enabled realtime on PG via adding my table, which is in public schema. In have RLS disabled. I have a user successfully signed in. Then I try to create a subscription via 
```channel = rep
            .channel('schema-db-changes')
            .on(
                'postgres_changes',
                {
                    event: '*',
                    schema: 'public',
                    table: 'demo',
                },
                (payload) => console.log(payload)
            )
            .subscribe()
```

Is there something else you think I should do? Thanks a lot

**Comment by datajohnny** [comment]
@w3b6x9 is there a way to bind request, all I am getting is connection refused when I try the command above

**Comment by w3b6x9** [comment]
@datajohnny that's my bad. that'll work if you're spinning up Realtime image by itself and its port 4000 is exposed.

**Comment by w3b6x9** [comment]
This issue should be resolved now. Both CLI (upgrade to v1.30.0) and self-hosting defaults `JWT_SECRET` to `API_JWT_SECRET` should it should just work out of the box.

**Comment by mr-moto** [comment]
confirmed working on my end thanks for the quick fix @w3b6x9 !!!

**Comment by damien22110** [comment]
Hello, if we use "jwt_secret": "super-secret-jwt-token-with-at-least-32-characters-long", in the post request, what will be the token used in the inspector supabase?

**Comment by w3b6x9** [comment]
> what will be the token used in the inspector supabase?

@damien22110 you can use either the anon token (https://github.com/supabase/cli/blob/650d0683c3dbf33c05b78fd54a0b268e334402c5/internal/utils/misc.go#L81) or service_role token (https://github.com/supabase/cli/blob/650d0683c3dbf33c05b78fd54a0b268e334402c5/internal/utils/misc.go#L82).

**Comment by yrodrigez** [comment]
Hey i'm very new to this but i also have this issue

I am using the windows cli to mount this on local and did the scoop update and also the  'supabase stop --no-backup' 
And still having these logs: 
2023-10-01 19:30:05 17:30:05.835 [debug] QUERY OK source="extensions" db=0.4ms idle=1310.2ms
2023-10-01 19:30:05 SELECT e0."id", e0."type", e0."settings", e0."tenant_external_id", e0."inserted_at", e0."updated_at", e0."tenant_external_id" FROM "extensions" AS e0 WHERE (e0."tenant_external_id" = $1) ORDER BY e0."tenant_external_id" ["realtime-dev"]
2023-10-01 19:30:05 17:30:05.836 project=realtime-dev external_id=realtime-dev [error] Auth error: {:error, :signature_error}
2023-10-01 19:30:10 17:30:10.986 project=realtime-dev external_id=realtime-dev [error] Auth error: {:error, :signature_error}
2023-10-01 19:30:17 17:30:17.039 project=realtime-dev external_id=realtime-dev [error] Auth error: {:error, :signature_error}
